# 关于Promise
使用Promise的时候有几点需要注意的

1. Promise构造函数接收的函数作为参数，这个函数是立即运行的，同时调用resolve或reject并不会阻止参数函数的运行
```javascript
const p = new Promise(function(resolve, reject) {
  console.log('a')
  resolve()
  console.log('b')
})
p.then(function(resolve, reject) {
  console.log('c')
})
console.log('d')

// 运行结果
// a b d c
```

2. resolve函数的参数除了可以是正常的值以外，也可以是一个Promise实例
```javascript
const p1 = new Promise(function (resolve, reject) {
  // ...
})

const p2 = new Promise(function (resolve, reject) {
  // ...
  resolve(p1)
})
```
p2此时会等待p1的状态变更，当p1变成resolve或者reject时，p2的回调函数才会立即执行，根据p1的状态决定p2是then还是reject
```javascript
const p1 = new Promise(function (resolve, reject) {
  setTimeout(() => reject(new Error('fail')), 3000)
})

const p2 = new Promise(function (resolve, reject) {
  setTimeout(() => resolve(p1), 1000)
})

p2
  .then(result => console.log(result))
  .catch(error => console.log(error))
// Error: fair
```
p2在1s的时候本来可以变更状态，但是由于resolve的参数是一个promise，则转变成等待该promise状态改变。  
3s后p1的状态变成rejected，所以p2也变成rejected

3. catch可以是reject函数被调用，也可以是内部抛出异常
```javascript
const p = new Promise((resolve, reject) => {
  throw new Error('this is an error')
})
p.catch(err => console.log(err))
// Error: this is an error
```

4. Promise的状态一旦改变便无法改变
```javascript
const promise = new Promise(function(resolve, reject) {
  resolve('ok')
  throw new Error('test')
})
promise
  .then(function(value) { console.log(value) })
  .catch(function(error) { console.log(error) })
// ok
```
由于promise已经将状态变为resolved，所以即使后续抛出异常test也是无效的。

5. Promise.resolve和Promise.reject
## Promise.resolve
Promise.resolve可以接收一个基本的值作为参数，也可以接收一个promise为参数，甚至可以接收一个thenable的对象
```javascript
Promise.resolve('done')

Promise.resolve(fs.readFile())

const obj = {
  then() {
    console.log('done')
    return 'done'
  }
}
Promise.resolve(obj) // done
```
当一个对象具备then方法，我们称之为thenable对象，当传入Promise.resolve时，会被立即执行then方法。

Promise.resolve()会返回promise对象，并且是在本轮“事件循环”的结束时，而不是下一轮“事件循环”的开始时
```javascript
setTimeout(() => {
  conmsole.log('tree')
}, 0)

Promise.resolve().then(() => console.log('two'))

console.log('one')

// one
// two
// three
```
由于setTimeout是在下一轮“事件循环”开始时执行，而Promise.resolve是在本轮“事件循环”结束时执行。

# Promise.reject
Promise.reject的参数只能被当做错误返回，即使它是个具备then方法的对象
```javascript
const thenable = {
  then() {
    console.log('done')
  }
}
const p = Promise.reject()
p.catch(err => {
  console.log(err.then === thenable)
})
```

# Timer
* setTimeout()
* setInterval()
* setImmediate()
* process.nextTick()

考虑如下代码
```javascript
setTimeout(() => console.log(1));  // ①
setImmediate(() => console.log(2)); // ②
process.nextTick(() => console.log(3)); // ③
Promise.resolve().then(() => console.log(4)); // ④
(() => console.log(5))(); // ⑤
```
运行结果
```
5
3
4
1
2
```

其中⑤先打印输出5毫无疑问，因为是同步的代码，执行到就直接输出了。

然后看异步的操作，异步循环分两种：
1. 追加在本轮循环的异步
2. 追加在次轮循环的异步

其中`process.nextTick`和`Promise`的回调函数，追加在本轮循环，即同步任务一旦执行完，就开始执行他们。  
而`setTimeout`、`setInterval`和`setImmediate`的回调函数，将在次轮循环中执行

因此上述代码③和④将会比①和②先执行。

当开始执行本轮循环的异步任务时，会先执行`process.nextTick`，它是所有异步任务里最快被执行的，因此③先被执行，④后被执行。  
此时执行顺序为⑤③④

## 异步循环阶段分析
当进入次轮循环，主线程会不断进行事件循环，每轮循环分成如下6个阶段
```
   ┌───────────────────────┐
┌─>│        timers         │
│  └──────────┬────────────┘
│  ┌──────────┴────────────┐
│  │     I/O callbacks     │
│  └──────────┬────────────┘
│  ┌──────────┴────────────┐
│  │     idle, prepare     │
│  └──────────┬────────────┘      ┌───────────────┐
│  ┌──────────┴────────────┐      │   incoming:   │
│  │         poll          │<─────┤  connections, │
│  └──────────┬────────────┘      │   data, etc.  │
│  ┌──────────┴────────────┐      └───────────────┘
│  │        check          │
│  └──────────┬────────────┘
│  ┌──────────┴────────────┐
└──┤    close callbacks    │
   └───────────────────────┘
```

1. timer阶段，检查timeer是否满足定时器要求，满足则执行，否则进行下一步。
2. i/o callback阶段，除了timer、setImmediate和close事件，一些系统操作的回调都会在该阶段执行。
3. idle,prepare阶段，是libuv内部调用
4. poll阶段，该阶段node会适当的阻塞在这里，如读文件。该阶段时间会比较长
5. check阶段，该阶段setImmediate的回调函数会被调用
6. close事件回调会被调用，如`socket.on('close')`

每个阶段都会有一个装有callbacks的队列queue，当event loop运行到指定的阶段时，node将执行该阶段的队列，当队列callbacks执行完或者执行callbacks数量超过该阶段的上限时，event loop将会转入下一阶段

### 详解poll阶段
这几个阶段中，大部分都好理解，其中poll阶段会比较复杂，也是衔接整个event loop中较为重要的阶段。  
在node.js里，任何异步方法（除timer,close,setImmediate之外）完成时，都会将其callback加到poll queue里,并立即执行。

poll阶段主要有两个功能：
1. 执行timers的callback，当到达timers指定的时间时
2. 处理poll队列（poll queue）的事件（callbacks）

如果event loop进入poll阶段，且代码未设定timer，将会发生如下情况：
* 如果poll queue不为空，event loop将同步的执行queue里callback，或执行的callback到达系统上限。
* 如果poll queue为空，将会发生下面情况：
    * 如果代码已经被setImmediate设定了callback，将结束poll阶段进入check阶段，并执行check阶段的queue
    * 如果代码没有设定setImmediate(callback)，event loop将阻塞在该阶段等待callbacks加入poll queue

如果event loop进入了 poll阶段，且代码设定了timer：
* 如果poll queue进入空状态时（即poll 阶段为空闲状态），event loop将检查timers,如果有1个或多个timers时间时间已经到达，event loop将按循环顺序进入timers阶段，并执行timer queue.

官方有个例，稍微简化下代码
```javascript
const fs = require('fs')

const timeoutScheduled = Date.now();

setTimeout(() => {
  const delay = Date.now() - timeoutScheduled
  console.log(`${delay}ms have passed since I was scheduled`)
}, 100)

fs.readFile('/path/to/file', () => {
  const startCallback = Date.now()
  
  while (Date.now() - startCallback < 10) {
    // doSomething
  }
})
```
1. 进入timer阶段，无callback到达，因为setTimeout需要100ms
2. i/o callback阶段，无异步i/o完成
3. 忽略
4. poll阶段，阻塞在这里，`fs.readFile`读取完成，可能花了95ms，将callback加入队列，并执行callback，该callback需要10ms的时间，结束后poll便处于空闲状态，便开始检查timers，发现timer设定的时间是100ms，此时已经到达105ms，超过了100ms，此时loop会回到timers阶段执行timer回调，最后输出时间是105ms左右

现在我们知道，setImmediate在check阶段才会被执行，在timer之后，因此大部分情况下都会慢于timer的相关函数，因此之前的例子先执行①再执行②，最终结果为⑤③④①②。

为什么说大部分，是因为虽然setTimeout的第二个参数默认为0，但是实际上Node是做不到0ms的，根据node的文档，该参数是一个介于1到2147483647，也即最少也需要1ms，即`setTimeout(fn, 0)`相当于`setTimeout(fn, 1)`

实际在执行的时候，可能到1ms了，也可能还没到1ms，如果没到1ms，那么timer阶段会被跳过，进入到check阶段，先执行setImmediate回调函数。
```javascript
const fs = require('fs')

fs.readFile('test.js', () => {
  setTimeout(() => console.log(1))
  setImmediate(() => console.log(2))
})
```
上述代码会先打印2再打印1。

该代码会先进入io阶段，然后是check阶段，等到文件读取完成，又会到timer阶段，此时没有timer，进入io阶段，发现可以执行readFile的回调函数了，回调函数有setTimeout和setImmediate，可是此时还没到可以执行setTimeout的timer阶段，因此无法执行其回调函数，同理也没到执行setImmediate回调函数的阶段。接下来就到了check阶段，此时执行setImmediate回调函数，结束后又到timer阶段执行setTimeout，因此才会出现先打印2打印1的情况。

因此如果需要在io操作中马上执行一个异步任务，应该优先使用setImmediate，它永远会先于setTimeout被执行到。

# 补充一下
我们已经知道process.nextTick并不属于事件循环的一部分，它会在代码块结束运行后，在事件循环开始前执行。

因此如果在process.nextTick回调函数里有很耗cpu的操作，也就等同于阻塞了事件循环的开始了。

既然如此为什么还要提供这样的api呢，被设计出来必然有它的原因。

```javascript
let bar;

function someAsyncApiCall(callback) { callback() }
someAsyncApiCall(() => {
  console.log('bar', bar); // undefined
})

bar = 1
```
代码打印出了bar为undefined，因为我们的callback是个同步操作，执行的时候bar并未赋值。

改变一下：
```javascript
let bar;

function someAsyncApiCall(callback) {
  process.nextTick(callback);
}

someAsyncApiCall(() => {
  console.log('bar', bar); // 1
});

bar = 1;
```
此时打印出bar为1，因为nextTick是在本轮代码执行结束后执行，此时bar已经有值了。

看一个我们日常使用的代码
```javascript
const server = net.createServer(() => {}).listen(8080)

server.on('listening', () => {})
```
根据node文档，listening事件的回调函数会在listen()方法被调用时马上触发执行，假设listen的代码如下：
```javascript
Server.prototype.listen = function (port) {
  // some code
  this.emit('listening')
}
```
由于在调用listen时`server.on('listening', () => {})`的代码还未被执行，因此回调函数无法被调用。我们改下代码
```javascript
Server.prototype.listen = function (port) {
  // some code
  process.nextTick(() => {
    this.emit('listening')
  })
}
```
这时listening事件的回调函数就可以被执行了，因为触发listening时，`server.on('listening', () => {})`已经执行了。

由上述例子我们也能知道方法emit是同步的，它会调用所有已经被注册的事件。

因此如果我们希望有些代码是在代码块执行结束之后立马被执行的，便可以使用process.nextTick
